# This is a basic workflow to help you get started with Actions

name: my-awesome-project - CI Trigger testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    steps:
        - name: my-awesome-project - Test
          run: echo "This is the test job."


        - name: my-awesome-project - Build
          run: echo "This is the build job."

        #- name: my-awesome-project - Bridge
         # uses: actions/checkout@master
          #with:
           # repository: kprbarani99/e2e-testing-qa
          
        - name: Trigger my e2e-testing-qa
          run: |
            #curl -XPOST -u "${{ secrets.GITHUB_TOKEN }}" -H "Accept:application/vnd.github" -H "Content-Type:application/json" https://api.github.com/repos/kprbarani99/e2e-testing-qa/e2e-testing-qa_action.yml/dispatches --data '{"ref": "main"}'   
            #echo "Trigger my e2e-testing-qa is completed now."
            echo "https://api.github.com/repos/kprbarani99/e2e-testing-qa/actions/workflows/e2e-testing-qa_action.yml/dispatches"

            curl -X POST "https://api.github.com/repos/kprbarani99/e2e-testing-qa/actions/workflows/e2e-testing-qa_action.yml/dispatches" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
              --data "{\"ref\":\"${ref}\",\"inputs\":${inputs}}"

        - name: my-awesome-project - Deploy
          run: echo "This is the deploy job."
