# This is a basic workflow to help you get started with Actions

name: my-awesome-project - CI Trigger testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  #image: alpine


    #stages:
     #   - test
      #  - build
       # - deploy

    # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

    steps:
        - name: my-awesome-project - Test
          run: echo "This is the test job."

    #build:
        #runs-on: ubuntu-latest

        - name: my-awesome-project - Build
          run: echo "This is the build job."
          
    #bridge:
    #stage: bridge
    #trigger: my-awesome-group-trigger/e2e-testing-qa
    
        - name: my-awesome-project - Bridge
          uses: actions/checkout@master
          with:
            repository: kprbarani99/e2e-testing-qa
            #run: echo "kprbarani99/e2e-testing-qa repo checkout successfully."

    #deploy:
        - name: my-awesome-project - Deploy
          run: echo "This is the deploy job."
